### ISSUE TITLE
[WinError 10054] An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by matbee-eth** [hkchengrex/Tracking-Anything-with-DEVA#14]
Has anyone seen this before? On Windows.

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 45/45 [00:11<00:00,  3.77it/s]
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\mail\.conda\envs\deva-tracking\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\mail\.conda\envs\deva-tracking\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

**Comment by Prasantkumar987** [comment]
Since Python 3.8 they change the default event loop on Windows to ProactorEventLoop instead of SelectorEventLoop and their are some issues with it.

Refer to this for detailed explanation and solution
https://stackoverflow.com/questions/62412754/python-asyncio-errors-oserror-winerror-6-the-handle-is-invalid-and-runtim
