### ISSUE TITLE
Something about the provided detection on VIPSeg 

### ISSUE THREAD

**Issue by chhchan** [hkchengrex/Tracking-Anything-with-DEVA#88]
I download the detection you provide on Google Drive, but find that some of the frames are missing (some of the videos like 1984_Km3UEW34R_Q), and it leads to error. How can I deal with it?
![20240508221824](https://github.com/hkchengrex/Tracking-Anything-with-DEVA/assets/169276775/d6c28d58-7db5-445f-b31c-399b7e68d90b)
![20240508221937](https://github.com/hkchengrex/Tracking-Anything-with-DEVA/assets/169276775/6fe38a15-ad9d-4b79-84a1-4ea121a28eaf)

**Comment by hkchengrex** [comment]
Here are the images in `1984_Km3UEW34R_Q` of my VIPSeg download:
00001488.jpg  00001494.jpg  00001497.jpg  00001500.jpg  00001503.jpg  00001506.jpg  00001509.jpg  00001512.jpg  00001515.jpg  00001518.jpg  00001521.jpg  00001524.jpg  00001527.jpg  00001530.jpg

I think the "missing" image is not provided by VIPSeg in the first place.

**Comment by hkchengrex** [comment]
Hmm... correction: they are in the raw `images` folder but not in the converted 720P version. Let me check.

**Comment by hkchengrex** [comment]
After some investigation, the problem is that I used the multi-threaded version of VIPSeg's conversion script: https://github.com/VIPSeg-Dataset/VIPSeg-Dataset/blob/main/change2_720p.py which contains a race condition when creating the folders. This leads to a silent failure of some of the threads and an incomplete conversion.

I apologize for the error. I found that 156 images failed to be converted, accounting for 0.19% of all images in the dataset (after the `change2_720p.py` step). I believe that this is insignificant for the final result and I will add a note for future reference.

The list contains the images that were successfully converted.
[converted-images.txt](https://github.com/hkchengrex/Tracking-Anything-with-DEVA/files/15253487/converted-images.txt)

You can ignore the images not listed in the txt during evaluation with our detections.
